Repository mlcommons/algorithmic-efficiency, pull requests merged in 2022-11, with the labels that each got.

#234 Fix usage of weights in WMT workloads + clean-up
  RULES.md
  algorithmic_efficiency/data_utils.py
  algorithmic_efficiency/spec.py
  algorithmic_efficiency/workloads/cifar/cifar_jax/input_pipeline.py
  algorithmic_efficiency/workloads/cifar/cifar_jax/workload.py
  algorithmic_efficiency/workloads/cifar/cifar_pytorch/workload.py
  algorithmic_efficiency/workloads/criteo1tb/criteo1tb_jax/workload.py
  algorithmic_efficiency/workloads/criteo1tb/criteo1tb_pytorch/workload.py
  algorithmic_efficiency/workloads/criteo1tb/input_pipeline.py
  algorithmic_efficiency/workloads/fastmri/fastmri_jax/workload.py
  algorithmic_efficiency/workloads/fastmri/fastmri_pytorch/workload.py
  algorithmic_efficiency/workloads/fastmri/input_pipeline.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_jax/input_pipeline.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_jax/workload.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_pytorch/workload.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_v2.py
  algorithmic_efficiency/workloads/librispeech_conformer/librispeech_jax/workload.py
  algorithmic_efficiency/workloads/librispeech_conformer/librispeech_pytorch/workload.py
  algorithmic_efficiency/workloads/librispeech_conformer/workload.py
  algorithmic_efficiency/workloads/mnist/mnist_jax/workload.py
  algorithmic_efficiency/workloads/mnist/mnist_pytorch/workload.py
  algorithmic_efficiency/workloads/ogbg/ogbg_jax/workload.py
  algorithmic_efficiency/workloads/ogbg/ogbg_pytorch/workload.py
  algorithmic_efficiency/workloads/ogbg/workload.py
  algorithmic_efficiency/workloads/wmt/input_pipeline.py
  algorithmic_efficiency/workloads/wmt/wmt_jax/workload.py
  algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py
  algorithmic_efficiency/workloads/wmt/workload.py
  reference_algorithms/development_algorithms/cifar/cifar_jax/submission.py
  reference_algorithms/development_algorithms/cifar/cifar_pytorch/submission.py
  reference_algorithms/development_algorithms/criteo1tb/criteo1tb_jax/submission.py
  reference_algorithms/development_algorithms/criteo1tb/criteo1tb_pytorch/submission.py
  reference_algorithms/development_algorithms/fastmri/fastmri_jax/submission.py
  reference_algorithms/development_algorithms/fastmri/fastmri_pytorch/submission.py
  reference_algorithms/development_algorithms/imagenet_resnet/imagenet_jax/submission.py
  reference_algorithms/development_algorithms/imagenet_resnet/imagenet_pytorch/submission.py
  reference_algorithms/development_algorithms/imagenet_vit/imagenet_jax/submission.py
  reference_algorithms/development_algorithms/imagenet_vit/imagenet_pytorch/submission.py
  reference_algorithms/development_algorithms/mnist/mnist_jax/submission.py
  reference_algorithms/development_algorithms/mnist/mnist_pytorch/submission.py
  reference_algorithms/development_algorithms/ogbg/ogbg_jax/submission.py
  reference_algorithms/development_algorithms/ogbg/ogbg_pytorch/submission.py
  reference_algorithms/development_algorithms/wmt/wmt_jax/submission.py
  reference_algorithms/development_algorithms/wmt/wmt_pytorch/submission.py
  reference_algorithms/target_setting_algorithms/jax_submission_base.py
  reference_algorithms/target_setting_algorithms/pytorch_submission_base.py
Labels: 🐛 Bug

#248 Jax ResNet Maxpool Padding
  algorithmic_efficiency/init_utils.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_jax/models.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_pytorch/models.py
Labels: 🧱 JAX

#251 NCCL Timeout Fix
  algorithmic_efficiency/checkpoint_utils.py
  algorithmic_efficiency/logger_utils.py
  submission_runner.py
Labels: 🐛 Bug

#254 Fix bleu score calculation for PyTorch WMT
  algorithmic_efficiency/data_utils.py
  algorithmic_efficiency/workloads/wmt/bleu.py
  algorithmic_efficiency/workloads/wmt/input_pipeline.py
  algorithmic_efficiency/workloads/wmt/wmt_jax/workload.py
  algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py
Labels: 🔥 PyTorch, 🐛 Bug

#239 Fix `loss_fn` in librispeech workloads
  algorithmic_efficiency/workloads/librispeech_conformer/librispeech_jax/workload.py
  algorithmic_efficiency/workloads/librispeech_conformer/librispeech_pytorch/workload.py
  reference_algorithms/development_algorithms/librispeech_conformer/librispeech_jax/submission.py
  reference_algorithms/development_algorithms/librispeech_conformer/librispeech_pytorch/submission.py
  reference_algorithms/development_algorithms/librispeech_deepspeech/librispeech_jax/submission.py
  reference_algorithms/development_algorithms/librispeech_deepspeech/librispeech_pytorch/submission.py
Labels: 🐛 Bug

#256 Check if optimizer state entry has state_dict() method
  RULES.md
  algorithmic_efficiency/checkpoint_utils.py
  algorithmic_efficiency/spec.py
Labels: 🐛 Bug

#267 Fix PyTorch ImageNet preprocessing with randaugment
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_pytorch/workload.py
Labels: 🔥 PyTorch, 🐛 Bug
