Repository mlcommons/algorithmic-efficiency, pull requests merged in 2022-10, with the labels that each got.

#155 Enable Jax to PyTorch array transfer on same device during decoding
  algorithmic_efficiency/workloads/wmt/decode.py
  algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py
Labels: ✨ Feature Request

#176 Fix recently introduced OGBG bugs
  algorithmic_efficiency/workloads/ogbg/input_pipeline.py
  algorithmic_efficiency/workloads/ogbg/workload.py
  tests/reference_submission_tests.py
Labels: 🐛 Bug

#196 Fix normalization for PyTorch ImageNet test split
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_pytorch/workload.py
Labels: 🐛 Bug

#209 Fix wrong eval metrics for FastMRI with PyTorch DDP
  algorithmic_efficiency/workloads/fastmri/fastmri_jax/workload.py
  algorithmic_efficiency/workloads/fastmri/fastmri_pytorch/workload.py
Labels: 🐛 Bug

#216 Gradient clipping fix
  reference_algorithms/target_setting_algorithms/pytorch_submission_base.py
Labels: 🐛 Bug

#229 ImageNet Pytorch Workload Processing Fix
  algorithmic_efficiency/data_utils.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_jax/input_pipeline.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_jax/randaugment.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_pytorch/randaugment.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_pytorch/workload.py
  algorithmic_efficiency/workloads/imagenet_vit/imagenet_pytorch/models.py
  reference_algorithms/target_setting_algorithms/pytorch_submission_base.py
Labels: 🔥 PyTorch, 🐛 Bug

#233 Pad remainder batch during eval
  algorithmic_efficiency/checkpoint_utils.py
  algorithmic_efficiency/data_utils.py
  algorithmic_efficiency/workloads/cifar/cifar_jax/input_pipeline.py
  algorithmic_efficiency/workloads/cifar/cifar_jax/workload.py
  algorithmic_efficiency/workloads/cifar/cifar_pytorch/workload.py
  algorithmic_efficiency/workloads/criteo1tb/criteo1tb_jax/metrics.py
  algorithmic_efficiency/workloads/criteo1tb/criteo1tb_jax/workload.py
  algorithmic_efficiency/workloads/criteo1tb/criteo1tb_pytorch/metrics.py
  algorithmic_efficiency/workloads/criteo1tb/criteo1tb_pytorch/workload.py
  algorithmic_efficiency/workloads/criteo1tb/input_pipeline.py
  algorithmic_efficiency/workloads/criteo1tb/workload.py
  algorithmic_efficiency/workloads/fastmri/fastmri_jax/workload.py
  algorithmic_efficiency/workloads/fastmri/fastmri_pytorch/workload.py
  algorithmic_efficiency/workloads/fastmri/input_pipeline.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_jax/input_pipeline.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_jax/workload.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_pytorch/workload.py
  algorithmic_efficiency/workloads/imagenet_resnet/imagenet_v2.py
  algorithmic_efficiency/workloads/mnist/mnist_jax/workload.py
  algorithmic_efficiency/workloads/mnist/workload.py
  algorithmic_efficiency/workloads/wmt/input_pipeline.py
  algorithmic_efficiency/workloads/wmt/wmt_jax/workload.py
  algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py
  submission_runner.py
Labels: 🐛 Bug
